// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: application_status.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type ApplicationStatus struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ApplicationStatus) Reset() {
	*x = ApplicationStatus{}
	mi := &file_application_status_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ApplicationStatus) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ApplicationStatus) ProtoMessage() {}

func (x *ApplicationStatus) ProtoReflect() protoreflect.Message {
	mi := &file_application_status_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ApplicationStatus.ProtoReflect.Descriptor instead.
func (*ApplicationStatus) Descriptor() ([]byte, []int) {
	return file_application_status_proto_rawDescGZIP(), []int{0}
}

func (x *ApplicationStatus) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *ApplicationStatus) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SubmitApplicationStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitApplicationStatusRequest) Reset() {
	*x = SubmitApplicationStatusRequest{}
	mi := &file_application_status_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitApplicationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitApplicationStatusRequest) ProtoMessage() {}

func (x *SubmitApplicationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_application_status_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitApplicationStatusRequest.ProtoReflect.Descriptor instead.
func (*SubmitApplicationStatusRequest) Descriptor() ([]byte, []int) {
	return file_application_status_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitApplicationStatusRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type SubmitApplicationStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitApplicationStatusResponse) Reset() {
	*x = SubmitApplicationStatusResponse{}
	mi := &file_application_status_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitApplicationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitApplicationStatusResponse) ProtoMessage() {}

func (x *SubmitApplicationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_application_status_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitApplicationStatusResponse.ProtoReflect.Descriptor instead.
func (*SubmitApplicationStatusResponse) Descriptor() ([]byte, []int) {
	return file_application_status_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitApplicationStatusResponse) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type UpdateApplicationStatusRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ApplicationStatus *ApplicationStatus     `protobuf:"bytes,1,opt,name=application_status,json=applicationStatus,proto3" json:"application_status,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateApplicationStatusRequest) Reset() {
	*x = UpdateApplicationStatusRequest{}
	mi := &file_application_status_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateApplicationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateApplicationStatusRequest) ProtoMessage() {}

func (x *UpdateApplicationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_application_status_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateApplicationStatusRequest.ProtoReflect.Descriptor instead.
func (*UpdateApplicationStatusRequest) Descriptor() ([]byte, []int) {
	return file_application_status_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateApplicationStatusRequest) GetApplicationStatus() *ApplicationStatus {
	if x != nil {
		return x.ApplicationStatus
	}
	return nil
}

type UpdateApplicationStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateApplicationStatusResponse) Reset() {
	*x = UpdateApplicationStatusResponse{}
	mi := &file_application_status_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateApplicationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateApplicationStatusResponse) ProtoMessage() {}

func (x *UpdateApplicationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_application_status_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateApplicationStatusResponse.ProtoReflect.Descriptor instead.
func (*UpdateApplicationStatusResponse) Descriptor() ([]byte, []int) {
	return file_application_status_proto_rawDescGZIP(), []int{4}
}

type DeleteApplicationStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteApplicationStatusRequest) Reset() {
	*x = DeleteApplicationStatusRequest{}
	mi := &file_application_status_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteApplicationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteApplicationStatusRequest) ProtoMessage() {}

func (x *DeleteApplicationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_application_status_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteApplicationStatusRequest.ProtoReflect.Descriptor instead.
func (*DeleteApplicationStatusRequest) Descriptor() ([]byte, []int) {
	return file_application_status_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteApplicationStatusRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteApplicationStatusResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteApplicationStatusResponse) Reset() {
	*x = DeleteApplicationStatusResponse{}
	mi := &file_application_status_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteApplicationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteApplicationStatusResponse) ProtoMessage() {}

func (x *DeleteApplicationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_application_status_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteApplicationStatusResponse.ProtoReflect.Descriptor instead.
func (*DeleteApplicationStatusResponse) Descriptor() ([]byte, []int) {
	return file_application_status_proto_rawDescGZIP(), []int{6}
}

type GetApplicationStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApplicationStatusRequest) Reset() {
	*x = GetApplicationStatusRequest{}
	mi := &file_application_status_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicationStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationStatusRequest) ProtoMessage() {}

func (x *GetApplicationStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_application_status_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationStatusRequest.ProtoReflect.Descriptor instead.
func (*GetApplicationStatusRequest) Descriptor() ([]byte, []int) {
	return file_application_status_proto_rawDescGZIP(), []int{7}
}

func (x *GetApplicationStatusRequest) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetApplicationStatusResponse struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	ApplicationStatus *ApplicationStatus     `protobuf:"bytes,1,opt,name=application_status,json=applicationStatus,proto3" json:"application_status,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *GetApplicationStatusResponse) Reset() {
	*x = GetApplicationStatusResponse{}
	mi := &file_application_status_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicationStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationStatusResponse) ProtoMessage() {}

func (x *GetApplicationStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_application_status_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationStatusResponse.ProtoReflect.Descriptor instead.
func (*GetApplicationStatusResponse) Descriptor() ([]byte, []int) {
	return file_application_status_proto_rawDescGZIP(), []int{8}
}

func (x *GetApplicationStatusResponse) GetApplicationStatus() *ApplicationStatus {
	if x != nil {
		return x.ApplicationStatus
	}
	return nil
}

type GetAllApplicationsStatusRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllApplicationsStatusRequest) Reset() {
	*x = GetAllApplicationsStatusRequest{}
	mi := &file_application_status_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllApplicationsStatusRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllApplicationsStatusRequest) ProtoMessage() {}

func (x *GetAllApplicationsStatusRequest) ProtoReflect() protoreflect.Message {
	mi := &file_application_status_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllApplicationsStatusRequest.ProtoReflect.Descriptor instead.
func (*GetAllApplicationsStatusRequest) Descriptor() ([]byte, []int) {
	return file_application_status_proto_rawDescGZIP(), []int{9}
}

type GetAllApplicationsStatusResponse struct {
	state               protoimpl.MessageState `protogen:"open.v1"`
	ApplicationStatuses []*ApplicationStatus   `protobuf:"bytes,1,rep,name=application_statuses,json=applicationStatuses,proto3" json:"application_statuses,omitempty"`
	unknownFields       protoimpl.UnknownFields
	sizeCache           protoimpl.SizeCache
}

func (x *GetAllApplicationsStatusResponse) Reset() {
	*x = GetAllApplicationsStatusResponse{}
	mi := &file_application_status_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllApplicationsStatusResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllApplicationsStatusResponse) ProtoMessage() {}

func (x *GetAllApplicationsStatusResponse) ProtoReflect() protoreflect.Message {
	mi := &file_application_status_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllApplicationsStatusResponse.ProtoReflect.Descriptor instead.
func (*GetAllApplicationsStatusResponse) Descriptor() ([]byte, []int) {
	return file_application_status_proto_rawDescGZIP(), []int{10}
}

func (x *GetAllApplicationsStatusResponse) GetApplicationStatuses() []*ApplicationStatus {
	if x != nil {
		return x.ApplicationStatuses
	}
	return nil
}

var File_application_status_proto protoreflect.FileDescriptor

const file_application_status_proto_rawDesc = "" +
	"\n" +
	"\x18application_status.proto\x12\x12application_status\"7\n" +
	"\x11ApplicationStatus\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\"4\n" +
	"\x1eSubmitApplicationStatusRequest\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"1\n" +
	"\x1fSubmitApplicationStatusResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"v\n" +
	"\x1eUpdateApplicationStatusRequest\x12T\n" +
	"\x12application_status\x18\x01 \x01(\v2%.application_status.ApplicationStatusR\x11applicationStatus\"!\n" +
	"\x1fUpdateApplicationStatusResponse\"0\n" +
	"\x1eDeleteApplicationStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"!\n" +
	"\x1fDeleteApplicationStatusResponse\"-\n" +
	"\x1bGetApplicationStatusRequest\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\"t\n" +
	"\x1cGetApplicationStatusResponse\x12T\n" +
	"\x12application_status\x18\x01 \x01(\v2%.application_status.ApplicationStatusR\x11applicationStatus\"!\n" +
	"\x1fGetAllApplicationsStatusRequest\"|\n" +
	" GetAllApplicationsStatusResponse\x12X\n" +
	"\x14application_statuses\x18\x01 \x03(\v2%.application_status.ApplicationStatusR\x13applicationStatusesB1Z/github.com/EduardMikhrin/territorial-fishermans/internal/typesb\x06proto3"

var (
	file_application_status_proto_rawDescOnce sync.Once
	file_application_status_proto_rawDescData []byte
)

func file_application_status_proto_rawDescGZIP() []byte {
	file_application_status_proto_rawDescOnce.Do(func() {
		file_application_status_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_application_status_proto_rawDesc), len(file_application_status_proto_rawDesc)))
	})
	return file_application_status_proto_rawDescData
}

var file_application_status_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_application_status_proto_goTypes = []any{
	(*ApplicationStatus)(nil),                // 0: application_status.ApplicationStatus
	(*SubmitApplicationStatusRequest)(nil),   // 1: application_status.SubmitApplicationStatusRequest
	(*SubmitApplicationStatusResponse)(nil),  // 2: application_status.SubmitApplicationStatusResponse
	(*UpdateApplicationStatusRequest)(nil),   // 3: application_status.UpdateApplicationStatusRequest
	(*UpdateApplicationStatusResponse)(nil),  // 4: application_status.UpdateApplicationStatusResponse
	(*DeleteApplicationStatusRequest)(nil),   // 5: application_status.DeleteApplicationStatusRequest
	(*DeleteApplicationStatusResponse)(nil),  // 6: application_status.DeleteApplicationStatusResponse
	(*GetApplicationStatusRequest)(nil),      // 7: application_status.GetApplicationStatusRequest
	(*GetApplicationStatusResponse)(nil),     // 8: application_status.GetApplicationStatusResponse
	(*GetAllApplicationsStatusRequest)(nil),  // 9: application_status.GetAllApplicationsStatusRequest
	(*GetAllApplicationsStatusResponse)(nil), // 10: application_status.GetAllApplicationsStatusResponse
}
var file_application_status_proto_depIdxs = []int32{
	0, // 0: application_status.UpdateApplicationStatusRequest.application_status:type_name -> application_status.ApplicationStatus
	0, // 1: application_status.GetApplicationStatusResponse.application_status:type_name -> application_status.ApplicationStatus
	0, // 2: application_status.GetAllApplicationsStatusResponse.application_statuses:type_name -> application_status.ApplicationStatus
	3, // [3:3] is the sub-list for method output_type
	3, // [3:3] is the sub-list for method input_type
	3, // [3:3] is the sub-list for extension type_name
	3, // [3:3] is the sub-list for extension extendee
	0, // [0:3] is the sub-list for field type_name
}

func init() { file_application_status_proto_init() }
func file_application_status_proto_init() {
	if File_application_status_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_application_status_proto_rawDesc), len(file_application_status_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_application_status_proto_goTypes,
		DependencyIndexes: file_application_status_proto_depIdxs,
		MessageInfos:      file_application_status_proto_msgTypes,
	}.Build()
	File_application_status_proto = out.File
	file_application_status_proto_goTypes = nil
	file_application_status_proto_depIdxs = nil
}
