// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: application.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// Application represents a fishing permit application record.
type Application struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientId      uint64                 `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	FishingDate   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=fishing_date,json=fishingDate,proto3" json:"fishing_date,omitempty"`
	Location      string                 `protobuf:"bytes,4,opt,name=location,proto3" json:"location,omitempty"`
	Status        string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Application) Reset() {
	*x = Application{}
	mi := &file_application_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Application) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Application) ProtoMessage() {}

func (x *Application) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Application.ProtoReflect.Descriptor instead.
func (*Application) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{0}
}

func (x *Application) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Application) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *Application) GetFishingDate() *timestamppb.Timestamp {
	if x != nil {
		return x.FishingDate
	}
	return nil
}

func (x *Application) GetLocation() string {
	if x != nil {
		return x.Location
	}
	return ""
}

func (x *Application) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *Application) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

type SubmitApplication struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	ClientId      uint64                 `protobuf:"varint,2,opt,name=client_id,json=clientId,proto3" json:"client_id,omitempty"`
	FishingDate   *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=fishing_date,json=fishingDate,proto3" json:"fishing_date,omitempty"`
	LocationId    uint64                 `protobuf:"varint,4,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	StatusId      uint64                 `protobuf:"varint,5,opt,name=status_id,json=statusId,proto3" json:"status_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitApplication) Reset() {
	*x = SubmitApplication{}
	mi := &file_application_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitApplication) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitApplication) ProtoMessage() {}

func (x *SubmitApplication) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitApplication.ProtoReflect.Descriptor instead.
func (*SubmitApplication) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitApplication) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *SubmitApplication) GetClientId() uint64 {
	if x != nil {
		return x.ClientId
	}
	return 0
}

func (x *SubmitApplication) GetFishingDate() *timestamppb.Timestamp {
	if x != nil {
		return x.FishingDate
	}
	return nil
}

func (x *SubmitApplication) GetLocationId() uint64 {
	if x != nil {
		return x.LocationId
	}
	return 0
}

func (x *SubmitApplication) GetStatusId() uint64 {
	if x != nil {
		return x.StatusId
	}
	return 0
}

func (x *SubmitApplication) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

// SubmitApplicationRequest carries the payload to create a new application.
type SubmitApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Application   *SubmitApplication     `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitApplicationRequest) Reset() {
	*x = SubmitApplicationRequest{}
	mi := &file_application_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitApplicationRequest) ProtoMessage() {}

func (x *SubmitApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitApplicationRequest.ProtoReflect.Descriptor instead.
func (*SubmitApplicationRequest) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitApplicationRequest) GetApplication() *SubmitApplication {
	if x != nil {
		return x.Application
	}
	return nil
}

type SubmitApplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId int64                  `protobuf:"varint,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitApplicationResponse) Reset() {
	*x = SubmitApplicationResponse{}
	mi := &file_application_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitApplicationResponse) ProtoMessage() {}

func (x *SubmitApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitApplicationResponse.ProtoReflect.Descriptor instead.
func (*SubmitApplicationResponse) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{3}
}

func (x *SubmitApplicationResponse) GetApplicationId() int64 {
	if x != nil {
		return x.ApplicationId
	}
	return 0
}

// DeleteApplicationRequest identifies an application to remove.
type DeleteApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId uint64                 `protobuf:"varint,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteApplicationRequest) Reset() {
	*x = DeleteApplicationRequest{}
	mi := &file_application_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteApplicationRequest) ProtoMessage() {}

func (x *DeleteApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteApplicationRequest.ProtoReflect.Descriptor instead.
func (*DeleteApplicationRequest) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{4}
}

func (x *DeleteApplicationRequest) GetApplicationId() uint64 {
	if x != nil {
		return x.ApplicationId
	}
	return 0
}

// DeleteApplicationResponse reports whether deletion was successful.
type DeleteApplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteApplicationResponse) Reset() {
	*x = DeleteApplicationResponse{}
	mi := &file_application_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteApplicationResponse) ProtoMessage() {}

func (x *DeleteApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteApplicationResponse.ProtoReflect.Descriptor instead.
func (*DeleteApplicationResponse) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{5}
}

// ListApplicationsRequest supports retrieving applications with pagination.
type ListApplicationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApplicationsRequest) Reset() {
	*x = ListApplicationsRequest{}
	mi := &file_application_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApplicationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApplicationsRequest) ProtoMessage() {}

func (x *ListApplicationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApplicationsRequest.ProtoReflect.Descriptor instead.
func (*ListApplicationsRequest) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{6}
}

// ListApplicationsResponse returns a page of applications and a token for the next page.
type ListApplicationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Applications  []*Application         `protobuf:"bytes,1,rep,name=applications,proto3" json:"applications,omitempty"`
	NextPageToken string                 `protobuf:"bytes,2,opt,name=next_page_token,json=nextPageToken,proto3" json:"next_page_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListApplicationsResponse) Reset() {
	*x = ListApplicationsResponse{}
	mi := &file_application_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListApplicationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListApplicationsResponse) ProtoMessage() {}

func (x *ListApplicationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListApplicationsResponse.ProtoReflect.Descriptor instead.
func (*ListApplicationsResponse) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{7}
}

func (x *ListApplicationsResponse) GetApplications() []*Application {
	if x != nil {
		return x.Applications
	}
	return nil
}

func (x *ListApplicationsResponse) GetNextPageToken() string {
	if x != nil {
		return x.NextPageToken
	}
	return ""
}

// GetApplicationByIdRequest identifies which application to fetch.
type GetApplicationByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	ApplicationId uint64                 `protobuf:"varint,1,opt,name=application_id,json=applicationId,proto3" json:"application_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApplicationByIdRequest) Reset() {
	*x = GetApplicationByIdRequest{}
	mi := &file_application_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicationByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationByIdRequest) ProtoMessage() {}

func (x *GetApplicationByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationByIdRequest.ProtoReflect.Descriptor instead.
func (*GetApplicationByIdRequest) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{8}
}

func (x *GetApplicationByIdRequest) GetApplicationId() uint64 {
	if x != nil {
		return x.ApplicationId
	}
	return 0
}

// GetApplicationByIdResponse returns the requested application.
type GetApplicationByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Application   *Application           `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetApplicationByIdResponse) Reset() {
	*x = GetApplicationByIdResponse{}
	mi := &file_application_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetApplicationByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetApplicationByIdResponse) ProtoMessage() {}

func (x *GetApplicationByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetApplicationByIdResponse.ProtoReflect.Descriptor instead.
func (*GetApplicationByIdResponse) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{9}
}

func (x *GetApplicationByIdResponse) GetApplication() *Application {
	if x != nil {
		return x.Application
	}
	return nil
}

// UpdateApplicationRequest carries the updated application data.
type UpdateApplicationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Application   *SubmitApplication     `protobuf:"bytes,1,opt,name=application,proto3" json:"application,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateApplicationRequest) Reset() {
	*x = UpdateApplicationRequest{}
	mi := &file_application_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateApplicationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateApplicationRequest) ProtoMessage() {}

func (x *UpdateApplicationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateApplicationRequest.ProtoReflect.Descriptor instead.
func (*UpdateApplicationRequest) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{10}
}

func (x *UpdateApplicationRequest) GetApplication() *SubmitApplication {
	if x != nil {
		return x.Application
	}
	return nil
}

// UpdateApplicationResponse returns the update status.
type UpdateApplicationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateApplicationResponse) Reset() {
	*x = UpdateApplicationResponse{}
	mi := &file_application_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateApplicationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateApplicationResponse) ProtoMessage() {}

func (x *UpdateApplicationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_application_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateApplicationResponse.ProtoReflect.Descriptor instead.
func (*UpdateApplicationResponse) Descriptor() ([]byte, []int) {
	return file_application_proto_rawDescGZIP(), []int{11}
}

var File_application_proto protoreflect.FileDescriptor

const file_application_proto_rawDesc = "" +
	"\n" +
	"\x11application.proto\x12\vapplication\x1a\x1fgoogle/protobuf/timestamp.proto\"\xe8\x01\n" +
	"\vApplication\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\x04R\bclientId\x12=\n" +
	"\ffishing_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vfishingDate\x12\x1a\n" +
	"\blocation\x18\x04 \x01(\tR\blocation\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\xf8\x01\n" +
	"\x11SubmitApplication\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x1b\n" +
	"\tclient_id\x18\x02 \x01(\x04R\bclientId\x12=\n" +
	"\ffishing_date\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\vfishingDate\x12\x1f\n" +
	"\vlocation_id\x18\x04 \x01(\x04R\n" +
	"locationId\x12\x1b\n" +
	"\tstatus_id\x18\x05 \x01(\x04R\bstatusId\x129\n" +
	"\n" +
	"created_at\x18\x06 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\"\\\n" +
	"\x18SubmitApplicationRequest\x12@\n" +
	"\vapplication\x18\x01 \x01(\v2\x1e.application.SubmitApplicationR\vapplication\"B\n" +
	"\x19SubmitApplicationResponse\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\x03R\rapplicationId\"A\n" +
	"\x18DeleteApplicationRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\x04R\rapplicationId\"\x1b\n" +
	"\x19DeleteApplicationResponse\"\x19\n" +
	"\x17ListApplicationsRequest\"\x80\x01\n" +
	"\x18ListApplicationsResponse\x12<\n" +
	"\fapplications\x18\x01 \x03(\v2\x18.application.ApplicationR\fapplications\x12&\n" +
	"\x0fnext_page_token\x18\x02 \x01(\tR\rnextPageToken\"B\n" +
	"\x19GetApplicationByIdRequest\x12%\n" +
	"\x0eapplication_id\x18\x01 \x01(\x04R\rapplicationId\"X\n" +
	"\x1aGetApplicationByIdResponse\x12:\n" +
	"\vapplication\x18\x01 \x01(\v2\x18.application.ApplicationR\vapplication\"\\\n" +
	"\x18UpdateApplicationRequest\x12@\n" +
	"\vapplication\x18\x01 \x01(\v2\x1e.application.SubmitApplicationR\vapplication\"\x1b\n" +
	"\x19UpdateApplicationResponseB1Z/github.com/EduardMikhrin/territorial-fishermans/internal/typesb\x06proto3"

var (
	file_application_proto_rawDescOnce sync.Once
	file_application_proto_rawDescData []byte
)

func file_application_proto_rawDescGZIP() []byte {
	file_application_proto_rawDescOnce.Do(func() {
		file_application_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_application_proto_rawDesc), len(file_application_proto_rawDesc)))
	})
	return file_application_proto_rawDescData
}

var file_application_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_application_proto_goTypes = []any{
	(*Application)(nil),                // 0: application.Application
	(*SubmitApplication)(nil),          // 1: application.SubmitApplication
	(*SubmitApplicationRequest)(nil),   // 2: application.SubmitApplicationRequest
	(*SubmitApplicationResponse)(nil),  // 3: application.SubmitApplicationResponse
	(*DeleteApplicationRequest)(nil),   // 4: application.DeleteApplicationRequest
	(*DeleteApplicationResponse)(nil),  // 5: application.DeleteApplicationResponse
	(*ListApplicationsRequest)(nil),    // 6: application.ListApplicationsRequest
	(*ListApplicationsResponse)(nil),   // 7: application.ListApplicationsResponse
	(*GetApplicationByIdRequest)(nil),  // 8: application.GetApplicationByIdRequest
	(*GetApplicationByIdResponse)(nil), // 9: application.GetApplicationByIdResponse
	(*UpdateApplicationRequest)(nil),   // 10: application.UpdateApplicationRequest
	(*UpdateApplicationResponse)(nil),  // 11: application.UpdateApplicationResponse
	(*timestamppb.Timestamp)(nil),      // 12: google.protobuf.Timestamp
}
var file_application_proto_depIdxs = []int32{
	12, // 0: application.Application.fishing_date:type_name -> google.protobuf.Timestamp
	12, // 1: application.Application.created_at:type_name -> google.protobuf.Timestamp
	12, // 2: application.SubmitApplication.fishing_date:type_name -> google.protobuf.Timestamp
	12, // 3: application.SubmitApplication.created_at:type_name -> google.protobuf.Timestamp
	1,  // 4: application.SubmitApplicationRequest.application:type_name -> application.SubmitApplication
	0,  // 5: application.ListApplicationsResponse.applications:type_name -> application.Application
	0,  // 6: application.GetApplicationByIdResponse.application:type_name -> application.Application
	1,  // 7: application.UpdateApplicationRequest.application:type_name -> application.SubmitApplication
	8,  // [8:8] is the sub-list for method output_type
	8,  // [8:8] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_application_proto_init() }
func file_application_proto_init() {
	if File_application_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_application_proto_rawDesc), len(file_application_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_application_proto_goTypes,
		DependencyIndexes: file_application_proto_depIdxs,
		MessageInfos:      file_application_proto_msgTypes,
	}.Build()
	File_application_proto = out.File
	file_application_proto_goTypes = nil
	file_application_proto_depIdxs = nil
}
