// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: location.proto

package types

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Location struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            uint64                 `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description   string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Photo         string                 `protobuf:"bytes,4,opt,name=photo,proto3" json:"photo,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Location) Reset() {
	*x = Location{}
	mi := &file_location_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Location) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Location) ProtoMessage() {}

func (x *Location) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Location.ProtoReflect.Descriptor instead.
func (*Location) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{0}
}

func (x *Location) GetId() uint64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *Location) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Location) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Location) GetPhoto() string {
	if x != nil {
		return x.Photo
	}
	return ""
}

type SubmitLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      *Location              `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitLocationRequest) Reset() {
	*x = SubmitLocationRequest{}
	mi := &file_location_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitLocationRequest) ProtoMessage() {}

func (x *SubmitLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitLocationRequest.ProtoReflect.Descriptor instead.
func (*SubmitLocationRequest) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{1}
}

func (x *SubmitLocationRequest) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

// Response after submitting (creating) a location
type SubmitLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationId    int64                  `protobuf:"varint,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubmitLocationResponse) Reset() {
	*x = SubmitLocationResponse{}
	mi := &file_location_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubmitLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubmitLocationResponse) ProtoMessage() {}

func (x *SubmitLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubmitLocationResponse.ProtoReflect.Descriptor instead.
func (*SubmitLocationResponse) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{2}
}

func (x *SubmitLocationResponse) GetLocationId() int64 {
	if x != nil {
		return x.LocationId
	}
	return 0
}

// Request to update a location
type UpdateLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      *Location              `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLocationRequest) Reset() {
	*x = UpdateLocationRequest{}
	mi := &file_location_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLocationRequest) ProtoMessage() {}

func (x *UpdateLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLocationRequest.ProtoReflect.Descriptor instead.
func (*UpdateLocationRequest) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{3}
}

func (x *UpdateLocationRequest) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

// Response after updating a location
type UpdateLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLocationResponse) Reset() {
	*x = UpdateLocationResponse{}
	mi := &file_location_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLocationResponse) ProtoMessage() {}

func (x *UpdateLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLocationResponse.ProtoReflect.Descriptor instead.
func (*UpdateLocationResponse) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{4}
}

// Request to delete a location
type DeleteLocationRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationId    uint64                 `protobuf:"varint,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLocationRequest) Reset() {
	*x = DeleteLocationRequest{}
	mi := &file_location_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLocationRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLocationRequest) ProtoMessage() {}

func (x *DeleteLocationRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLocationRequest.ProtoReflect.Descriptor instead.
func (*DeleteLocationRequest) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{5}
}

func (x *DeleteLocationRequest) GetLocationId() uint64 {
	if x != nil {
		return x.LocationId
	}
	return 0
}

// Response after deleting a location
type DeleteLocationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteLocationResponse) Reset() {
	*x = DeleteLocationResponse{}
	mi := &file_location_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteLocationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteLocationResponse) ProtoMessage() {}

func (x *DeleteLocationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteLocationResponse.ProtoReflect.Descriptor instead.
func (*DeleteLocationResponse) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{6}
}

// Request to get all locations
type GetAllLocationsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllLocationsRequest) Reset() {
	*x = GetAllLocationsRequest{}
	mi := &file_location_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllLocationsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllLocationsRequest) ProtoMessage() {}

func (x *GetAllLocationsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllLocationsRequest.ProtoReflect.Descriptor instead.
func (*GetAllLocationsRequest) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{7}
}

// Response with all locations
type GetAllLocationsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Locations     []*Location            `protobuf:"bytes,1,rep,name=locations,proto3" json:"locations,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAllLocationsResponse) Reset() {
	*x = GetAllLocationsResponse{}
	mi := &file_location_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAllLocationsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAllLocationsResponse) ProtoMessage() {}

func (x *GetAllLocationsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAllLocationsResponse.ProtoReflect.Descriptor instead.
func (*GetAllLocationsResponse) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{8}
}

func (x *GetAllLocationsResponse) GetLocations() []*Location {
	if x != nil {
		return x.Locations
	}
	return nil
}

// Request to get a location by ID
type GetLocationByIdRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LocationId    uint64                 `protobuf:"varint,1,opt,name=location_id,json=locationId,proto3" json:"location_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocationByIdRequest) Reset() {
	*x = GetLocationByIdRequest{}
	mi := &file_location_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationByIdRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationByIdRequest) ProtoMessage() {}

func (x *GetLocationByIdRequest) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationByIdRequest.ProtoReflect.Descriptor instead.
func (*GetLocationByIdRequest) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{9}
}

func (x *GetLocationByIdRequest) GetLocationId() uint64 {
	if x != nil {
		return x.LocationId
	}
	return 0
}

// Response with a single location
type GetLocationByIdResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Location      *Location              `protobuf:"bytes,1,opt,name=location,proto3" json:"location,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetLocationByIdResponse) Reset() {
	*x = GetLocationByIdResponse{}
	mi := &file_location_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetLocationByIdResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetLocationByIdResponse) ProtoMessage() {}

func (x *GetLocationByIdResponse) ProtoReflect() protoreflect.Message {
	mi := &file_location_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetLocationByIdResponse.ProtoReflect.Descriptor instead.
func (*GetLocationByIdResponse) Descriptor() ([]byte, []int) {
	return file_location_proto_rawDescGZIP(), []int{10}
}

func (x *GetLocationByIdResponse) GetLocation() *Location {
	if x != nil {
		return x.Location
	}
	return nil
}

var File_location_proto protoreflect.FileDescriptor

const file_location_proto_rawDesc = "" +
	"\n" +
	"\x0elocation.proto\x12\blocation\"f\n" +
	"\bLocation\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x04R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12\x14\n" +
	"\x05photo\x18\x04 \x01(\tR\x05photo\"G\n" +
	"\x15SubmitLocationRequest\x12.\n" +
	"\blocation\x18\x01 \x01(\v2\x12.location.LocationR\blocation\"9\n" +
	"\x16SubmitLocationResponse\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\x03R\n" +
	"locationId\"G\n" +
	"\x15UpdateLocationRequest\x12.\n" +
	"\blocation\x18\x01 \x01(\v2\x12.location.LocationR\blocation\"\x18\n" +
	"\x16UpdateLocationResponse\"8\n" +
	"\x15DeleteLocationRequest\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\x04R\n" +
	"locationId\"\x18\n" +
	"\x16DeleteLocationResponse\"\x18\n" +
	"\x16GetAllLocationsRequest\"K\n" +
	"\x17GetAllLocationsResponse\x120\n" +
	"\tlocations\x18\x01 \x03(\v2\x12.location.LocationR\tlocations\"9\n" +
	"\x16GetLocationByIdRequest\x12\x1f\n" +
	"\vlocation_id\x18\x01 \x01(\x04R\n" +
	"locationId\"I\n" +
	"\x17GetLocationByIdResponse\x12.\n" +
	"\blocation\x18\x01 \x01(\v2\x12.location.LocationR\blocationB1Z/github.com/EduardMikhrin/territorial-fishermans/internal/typesb\x06proto3"

var (
	file_location_proto_rawDescOnce sync.Once
	file_location_proto_rawDescData []byte
)

func file_location_proto_rawDescGZIP() []byte {
	file_location_proto_rawDescOnce.Do(func() {
		file_location_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_location_proto_rawDesc), len(file_location_proto_rawDesc)))
	})
	return file_location_proto_rawDescData
}

var file_location_proto_msgTypes = make([]protoimpl.MessageInfo, 11)
var file_location_proto_goTypes = []any{
	(*Location)(nil),                // 0: location.Location
	(*SubmitLocationRequest)(nil),   // 1: location.SubmitLocationRequest
	(*SubmitLocationResponse)(nil),  // 2: location.SubmitLocationResponse
	(*UpdateLocationRequest)(nil),   // 3: location.UpdateLocationRequest
	(*UpdateLocationResponse)(nil),  // 4: location.UpdateLocationResponse
	(*DeleteLocationRequest)(nil),   // 5: location.DeleteLocationRequest
	(*DeleteLocationResponse)(nil),  // 6: location.DeleteLocationResponse
	(*GetAllLocationsRequest)(nil),  // 7: location.GetAllLocationsRequest
	(*GetAllLocationsResponse)(nil), // 8: location.GetAllLocationsResponse
	(*GetLocationByIdRequest)(nil),  // 9: location.GetLocationByIdRequest
	(*GetLocationByIdResponse)(nil), // 10: location.GetLocationByIdResponse
}
var file_location_proto_depIdxs = []int32{
	0, // 0: location.SubmitLocationRequest.location:type_name -> location.Location
	0, // 1: location.UpdateLocationRequest.location:type_name -> location.Location
	0, // 2: location.GetAllLocationsResponse.locations:type_name -> location.Location
	0, // 3: location.GetLocationByIdResponse.location:type_name -> location.Location
	4, // [4:4] is the sub-list for method output_type
	4, // [4:4] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_location_proto_init() }
func file_location_proto_init() {
	if File_location_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_location_proto_rawDesc), len(file_location_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   11,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_location_proto_goTypes,
		DependencyIndexes: file_location_proto_depIdxs,
		MessageInfos:      file_location_proto_msgTypes,
	}.Build()
	File_location_proto = out.File
	file_location_proto_goTypes = nil
	file_location_proto_depIdxs = nil
}
